# Generated by Django 4.2.1 on 2023-06-06 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="name",
            new_name="title",
        ),
    ]
